<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean" %>
<%@ taglib uri="http://struts.apache.org/tags-logic" prefix="logic" %>
<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<div class="centeredImage">
	<logic:lessThan name="overviewform" property="pagePrev" value="0"><a href="listkontobestellungen.do?method=overview&sort=mediatype&sortorder=asc&yfrom=<bean:write name="overviewform" property="yfrom" />&mfrom=<bean:write name="overviewform" property="mfrom" />&dfrom=<bean:write name="overviewform" property="dfrom" />&yto=<bean:write name="overviewform" property="yto" />&mto=<bean:write name="overviewform" property="mto" />&dto=<bean:write name="overviewform" property="dto" /><logic:present name="overviewform" property="filter">&filter=<bean:write name="overviewform" property="filter" /></logic:present><logic:present name="overviewform" property="s">&s=<bean:write name="overviewform" property="s" /></logic:present>&page=0"> <img src='img/left.png' alt="<bean:message key="uebersicht.previous" />" title="<bean:message key="uebersicht.previous" />" ></a></logic:lessThan><logic:greaterThan name="overviewform" property="pagePrev" value="0"><a href="listkontobestellungen.do?method=overview&sort=mediatype&sortorder=asc&yfrom=<bean:write name="overviewform" property="yfrom" />&mfrom=<bean:write name="overviewform" property="mfrom" />&dfrom=<bean:write name="overviewform" property="dfrom" />&yto=<bean:write name="overviewform" property="yto" />&mto=<bean:write name="overviewform" property="mto" />&dto=<bean:write name="overviewform" property="dto" /><logic:present name="overviewform" property="filter">&filter=<bean:write name="overviewform" property="filter" /></logic:present><logic:present name="overviewform" property="s">&s=<bean:write name="overviewform" property="s" /></logic:present>&page=<bean:write name="overviewform" property="pagePrev" />"> <img src='img/left.png' alt="<bean:message key="uebersicht.previous" />" title="<bean:message key="uebersicht.previous" />" ></a></logic:greaterThan><logic:greaterThan name="overviewform" property="pageNext" value="0"><a href="listkontobestellungen.do?method=overview&sort=mediatype&sortorder=asc&yfrom=<bean:write name="overviewform" property="yfrom" />&mfrom=<bean:write name="overviewform" property="mfrom" />&dfrom=<bean:write name="overviewform" property="dfrom" />&yto=<bean:write name="overviewform" property="yto" />&mto=<bean:write name="overviewform" property="mto" />&dto=<bean:write name="overviewform" property="dto" /><logic:present name="overviewform" property="filter">&filter=<bean:write name="overviewform" property="filter" /></logic:present><logic:present name="overviewform" property="s">&s=<bean:write name="overviewform" property="s" /></logic:present>&page=<bean:write name="overviewform" property="pageNext" />"> <img src='img/right.png' alt="<bean:message key="uebersicht.next" />" title="<bean:message key="uebersicht.next" />" ></a></logic:greaterThan>
</div>




